### PR TITLE
Initial pre-release

### PR DESCRIPTION
**Pull request by YeshwiniR**
@hacktron95 I think what's left is to implement the code of the `viewAnalytics` listener.

### CODE REVIEW

**Comment by hacktron95** [comment]
hey @YeshwiniR, let's first merge this and we can implement that listener in a separated feature branch lah

**Comment by hacktron95** [comment]
hey @LUXIANZE, please take a look :+1:

**Review by hacktron95 — APPROVED** [review]

**Comment by hacktron95** [comment]
LGTM since I was reviewing yesh's code on each commit

**Review by LUXIANZE — APPROVED** [review]

**Comment by LUXIANZE** [comment]
Fixes #6

**Pull request merged**
